---
AWSTemplateFormatVersion: '2010-09-09'
Description: Snyk integration for AWS Lambda. (qs-1qqfgjgbc)
Outputs:
  SnykLambdaIntegrationRole:
    Description: Snyk Lambda Integration Role ARN
    Value: !GetAtt 'SnykLambdaIntegrationRole.Arn'
  Version:
    Description: Snyk Lambda Integration Version
    Value: 1.0.2
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Snyk integration for AWS Lambda"
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk
        Parameters:
          - SnykExternalId
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      SnykExternalId:
        default: Snyk organization ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  SnykExternalId:
    Description: You may find this by logging into https://app.snyk.io and navigating to Settings.
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 1
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description:
      S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription:
      Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: quickstart-snyk-security/
    Description:
      S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
Resources:
  SnykLambdaIntegrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::198361731867:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'SnykExternalId'
      Path: /snyk/
      Policies:
        - PolicyName: SnykReadOnlyForLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  [
                    'lambda:ListFunctions',
                    'lambda:GetFunction',
                    'lambda:ListAliases',
                    'lambda:GetAccountSettings'
                  ]
                Resource: '*'
